# fly.toml app configuration file generated for chirimen on 2025-08-08T23:00:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chirimen'
kill_signal = 'SIGINT'
kill_timeout = '5s'
primary_region = 'nrt'

[env]
NTFY_GLOBAL_TOPIC_LIMIT = '30000'
NTFY_VISITOR_SUBSCRIPTION_LIMIT = '120'

[http_service]
auto_start_machines = true
auto_stop_machines = 'stop'
force_https = true
internal_port = 80
min_machines_running = 0
processes = ['app']

[[services]]
internal_port = 80
processes = ['app']
protocol = 'tcp'

[[services.ports]]
force_https = true
handlers = ['http']
port = 80

[[services.ports]]
handlers = ['tls', 'http']
port = 443

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = 'connections'

[[services.tcp_checks]]
grace_period = '1s'
interval = '15s'
timeout = '2s'

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '512mb'
